name: Build macOS

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        brew update
        brew install \
          cmake \
          ninja \
          pkg-config \
          python3 \
          git \
          wget \
          curl \
          radare2
          
    - name: Install Python dependencies
      run: |
        python3 -m venv .venv
        source .venv/bin/activate
        python -m pip install --upgrade pip
        python -m pip install pyyaml
        
    - name: Build project
      run: |
        chmod +x Scripts/Build.sh
        source .venv/bin/activate
        bash Scripts/Build.sh
        
    - name: Collect runtime binaries
      run: |
        mkdir -p artifacts
        
        # Show what was built
        echo "=== Contents of $HOME/.local ==="
        find $HOME/.local -type f | head -20
        
        # Collect only shared libraries (.dylib and .so files)
        find $HOME/.local/lib -name "*.dylib*" -exec cp {} artifacts/ \; 2>/dev/null || true
        find $HOME/.local/lib -name "*.so*" -exec cp {} artifacts/ \; 2>/dev/null || true
        
        # Collect radare2 plugin
        PLUGIN_DIR=$(radare2 -H R2_USER_PLUGINS 2>/dev/null) || PLUGIN_DIR=""
        if [ -n "$PLUGIN_DIR" ] && [ -d "$PLUGIN_DIR" ]; then
          find "$PLUGIN_DIR" -name "*reai*" -exec cp {} artifacts/ \; 2>/dev/null || true
        fi
        
        # Show what we collected
        echo "=== Collected Runtime Binaries ==="
        find artifacts -type f | sort
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: reai-r2-macos-binaries
        path: artifacts/
        if-no-files-found: warn 