name: Build Windows

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup MSVC
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Setup Visual Studio Developer Environment
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
        
    - name: Build project with Python venv
      run: |
        # Create and activate virtual environment
        python -m venv .venv
        .\.venv\Scripts\Activate.ps1
        
        # Install Python dependencies
        python -m pip install --upgrade pip
        python -m pip install pyyaml
        
        # Verify PyYAML is available
        python -c "import yaml; print('PyYAML is available in venv')"
        
        # Run the build script
        Set-ExecutionPolicy Bypass -Scope Process -Force
        .\Scripts\Build.ps1
      shell: powershell
      
    - name: Collect runtime binaries
      run: |
        New-Item -ItemType Directory -Force -Path "artifacts"
        
        $InstallPath = "$env:USERPROFILE\.local\RevEngAI\Radare2\Install"
        
        Write-Host "=== Contents of Install Directory ==="
        if (Test-Path $InstallPath) {
          Get-ChildItem -Recurse $InstallPath | Select-Object -First 30 | ForEach-Object { Write-Host $_.FullName }
          
          Write-Host "`n=== Collecting Our Built Libraries (.dll) ==="
          # Collect only our built libraries (exclude radare2 system DLLs)
          Get-ChildItem -Recurse $InstallPath -Filter "*.dll" | Where-Object { 
            $_.Name -notlike "r_*.dll" -and $_.Name -notlike "radare2*.dll" 
          } | ForEach-Object {
            Copy-Item $_.FullName "artifacts\"
            Write-Host "Copied DLL: $($_.Name)"
          }
          
          Write-Host "`n=== Collecting Our Built Import Libraries (.lib) ==="
          # Collect import libraries for our built libraries (exclude radare2 system LIBs)
          Get-ChildItem -Recurse $InstallPath -Filter "*.lib" | Where-Object { 
            $_.Name -notlike "r_*.lib" -and $_.Name -notlike "radare2*.lib" 
          } | ForEach-Object {
            Copy-Item $_.FullName "artifacts\"
            Write-Host "Copied LIB: $($_.Name)"
          }
          
          # Look specifically for the plugin in radare2 plugin directory
          Write-Host "`n=== Looking for reai_radare plugin ==="
          try {
            $PluginDir = cmd /c "radare2 -H R2_USER_PLUGINS" 2>$null
            if ($PluginDir -and (Test-Path $PluginDir)) {
              Write-Host "Plugin directory: $PluginDir"
              Get-ChildItem $PluginDir -Filter "*reai*" -ErrorAction SilentlyContinue | ForEach-Object {
                Copy-Item $_.FullName "artifacts\"
                Write-Host "Copied plugin: $($_.Name)"
              }
            }
          } catch {
            Write-Host "Could not determine plugin directory, searching install path for plugin..."
            Get-ChildItem -Recurse $InstallPath -Filter "*reai_radare*" -ErrorAction SilentlyContinue | ForEach-Object {
              Copy-Item $_.FullName "artifacts\"
              Write-Host "Found plugin: $($_.Name)"
            }
          }
        } else {
          Write-Host "Install path not found: $InstallPath"
        }
        
        # Search build directories for any missed plugin files (.dll and .lib)
        Write-Host "`n=== Searching build directories for plugin files ==="
        Get-ChildItem -Recurse . -Filter "*reai_radare*" -ErrorAction SilentlyContinue | ForEach-Object {
          Copy-Item $_.FullName "artifacts\" -ErrorAction SilentlyContinue
          Write-Host "Found in build: $($_.Name)"
        }
        
        # Search build directories for any missed reai library files
        Write-Host "`n=== Searching build directories for reai library files ==="
        @("*reai.dll", "*reai.lib") | ForEach-Object {
          Get-ChildItem -Recurse . -Filter $_ -ErrorAction SilentlyContinue | ForEach-Object {
            Copy-Item $_.FullName "artifacts\" -ErrorAction SilentlyContinue
            Write-Host "Found reai library: $($_.Name)"
          }
        }
        
        Write-Host "`n=== Final Runtime Binaries ==="
        $files = Get-ChildItem "artifacts"
        if ($files) {
          $files | Sort-Object Name | ForEach-Object { Write-Host "$($_.Name) ($($_.Length) bytes)" }
        } else {
          Write-Host "WARNING: No artifacts were collected!"
        }
      shell: powershell
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: reai-r2-windows-binaries
        path: artifacts/
        if-no-files-found: warn 